apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-chaos-monkey
  namespace: chaos
  labels:
    app: chaos-monkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-chaos-monkey
  template:
    metadata:
      labels:
        app: pod-chaos-monkey
    spec:
      serviceAccountName: pod-chaos-monkey-sa
      containers:
        - name: chaos-monkey
          image: yisusisback/pod-chaos-monkey:0.0.1
          envFrom:
            - configMapRef:
                name: pod-chaos-monkey-config
          resources:
            limits:
              cpu: 100m
              memory: 128M
          volumeMounts:
            - name: blacklist-config
              mountPath: /app/blacklist.yml
              subPath: blacklist.yml
              readOnly: true
      volumes:
        - name: blacklist-config
          configMap:
            name: pod-chaos-monkey-blacklist
            items:
              - key: blacklist.yml
                path: blacklist.yml
