apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-chaos-monkey-config
  namespace: chaos
data:
  NAMESPACE: "workloads"
  SCHEDULE: "*/10 * * * * *"
  SCHEDULE_FORMAT: "cron-seconds"
  IS_INSIDE_CLUSTER: "true"
