apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-monkey
subjects:
  - kind: ServiceAccount
    name: pod-chaos-monkey-sa
    apiGroup: ""
    namespace: chaos
roleRef:
  kind: ClusterRole
  name: pod-deleter
  apiGroup: rbac.authorization.k8s.io
